#!/bin/ksh


file="/sbTibco/tibcoesb/adm_script/scripts/test_prova"
if [ ! -f $file ]; then
    echo "File not found!"
else
	while read -r line 
	do
		user=`echo $line | awk -F "," {' print  $1 '}`
		password=`echo $line | awk -F "," {' print  $2 '}`
		TNS_NAME=`echo $line | awk -F "," {' print  $3 '}`
sqlplus $user/$password@$TNS_NAME << EOF
alter user $user identified by "$password" replace "$password";
EOF
done < $file
fi
